lyft/metadataproxy

- Dockerfile.private
Add private Dockerfile for metadataproxy so that default Dockerfile can be the public, third-party usable file
> Add private Dockerfile for metadataproxy

- metadataproxy/roles.py
I have an environment variable with no value. Here's a snippet:
```
"Config": {
"Env": [
"TERM=xterm",
"HOST_PRIVATE_IP_ADDRESS",         <--
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
],
}
```
This variable makes `get_role_name_from_ip` fail, because `split()` returns 1 item instead of the expected 2. The fix below uses `partition()` instead of `split()`, which will always return a 3-tuple.
```
>>> e1 = 'TERM=xterm'
>>> e2 = 'HOST_PRIVATE_IP_ADDRESS'
>>> e1.split('=')
['TERM', 'xterm']
>>> e2.split('=')
['HOST_PRIVATE_IP_ADDRESS']
>>> e1.partition('=')
('TERM', '=', 'xterm')
>>> e2.partition('=')
('HOST_PRIVATE_IP_ADDRESS', '', '')
```
> Support environment variables that do not have a value

- Dockerfile
- README.md
- run-server.sh
As it currently stands, metadataproxy requires access to private lyft images which provide a lot of the startup config for metadataproxy.  This includes changes to run metadataproxy without lyft's gunicorn container config.
> Help non-lyft folks run metadataproxy

- metadataproxy/roles.py
- metadataproxy/routes/mock.py
- metadataproxy/routes/proxy.py
- metadataproxy/settings.py
This change adds support for assuming cross-account roles. The refactor also makes it possible to drop IAM:GET_ROLE permissions from metadataproxy's IAM role/user. Two new settings are added:
* DEFAULT_ACCOUNT_ID
* AWS_ACCOUNT_MAP
The behavior change here is reflected in the IAM_ROLE environment variable that's set. So, for instance the following environment variable uses a role in the default account:
```
IAM_ROLE=my-service-role
```
The following environment variable uses a role in another account:
```
IAM_ROLE=my-service-role@12345
```
By setting AWS_ACCOUNT_MAP it's possible to refer to accounts by a user-friendly name, rather than an ID:
```
export AWS_ACCOUNT_MAP='{"primary-account":"12345","security-account":"98765"}'
```
Then you can set an environment variable like the following: …
> Support assuming roles across accounts

- metadataproxy/routes/proxy.py
While troubleshooting an issue where containers get host role credentials, I found two ways in which metadataproxy differs from the upstream meta-data service.  In brief these changes:
1) Don't answer IAM requests for meta-data API versions that don't support IAM.
2) Follow AWS behavior when a client request has some trailing garbage
3) Use the DEBUG environment variable to get logs.
I think the second item is the fix I need - without it, metadataproxy leaks the host role.  But I don't have a good reproducible case there.
Thanks,
Ross
> Behavior fixes

- metadataproxy/roles.py
Pull Request for Issue #19
This change checks to see if the cached container is running and if its not, removes it from the cache. 
This will 1, prevent returning the role for the last container that had it's ip address and 2 help keep the cache clean of stopped containers.
> Handle cached containers that are stopped

- README.md
- metadataproxy/roles.py
- run-server.sh
Fixes issue #37 with allowing the IP match to check against NetworkSettings:Network:"netname":IPAddress as well as NetworkSettings:IPAddress which is not always set.
Also adds logging via gunicorn and some documentation updates.
> allow check to sub network for IP match, update docs, add logging

- CHANGELOG.md
- README.md
- metadataproxy/roles.py
- metadataproxy/routes/mock.py
- metadataproxy/routes/proxy.py
- metadataproxy/settings.py
- requirements_wsgi.txt
- setup.py
* IAM_EXTERNAL_ID variable; if found value will be populated into ExternalId parameter when making AssumeRole call.
* ROLE_SESSION_KEY variable; if found will use value to look up key from Docker container labels or environment variable to set RoleSessionName when making AssumeRole call.
* Reduce number of calls to Docker API when retrieving credentials.
* Bump WSGI versions to add support for gunicorn --capture-output option
* Set up logging when not run in debug mode
> Support for additional control over assumed roles

- metadataproxy/roles.py
This is a replacement for https://github.com/lyft/metadataproxy/pull/35 which passes the tests and implements the improvements listed on it
> New support retrieving container IP from Rancher labels

- entrypoint.sh
- manifest.yaml
- metadataproxy/settings.py
- provision.sh
`45001` is in the Linux ephemeral port range, and using it might be causing startup failures when destroying and restarting the metadataproxy container. Moving onto `4501` instead.
> Use port 4501

- README.md
The README didn't reference the fully qualified `lyft/metadataproxy` docker image name (it was missing the `lyft` namespace)
> Correct the docker image reference in the README

- metadataproxy/routes/proxy.py
After the update to the latest datadog agent (v6), we discovered that metadataproxy would not forward the correct status code for proxied requests.
In our specific case, the datadog agent would use the metadata API for Azure and GCE to detect hostnames. Azure and GCE use the same endpoint as AWS does (169.254.169.254) but different routes. The way datadog implemented the code is: if status code 404 discard response, if not, use response without further validation. So we ended up having hosts named after a 404 page which would break the Datadog UI. Forwarding the status code as well for proxied requests fixed the issue for us.
I am happy to open an issue if further discussion is required.
> Return correct status code for proxied requests

- manifest.yaml
need to be careful this doesn't break things, I haven't had time to verify but wanted to put a review out
> Disable "front envoy" routes for metadataproxy

- metadataproxy/routes/mock.py
This PR would address https://github.com/lyft/metadataproxy/issues/83
> Update mock URI for returning availability-zone

- Dockerfile.private
- gunicorn.conf
- manifest.yaml
Using the `lyft/gunicorn:fdbc8191800c582fbf63a208d84842148d1bde6c` image means that gunicorn is stuck on v19.4.5. We need it to be at least 19.8 to enable the `reload_extra_files = ['/root/.aws/credentials']` flag (required because this file will change frequently with ephemeral role credentials).
Changes:
* Switched to using imagebase image
* This imagebase image does not include virtualenv nor does it include /etc/gunicorn/gunicorn.conf so I am adding the installation of virtualenv and also the management of the gunicorn.conf file here (Happy for alternatives for the gunicorn.conf file location)
* Install requirements_wsgi.txt for gunicorn v19.9
> Upgrade gunicorn for Lyft's MDP

- metadataproxy/roles.py
A string that starts with `arn:aws` would match the "oh, extract a role from an ARN" code, but would fail if the regex didn't match. Here's a sample fail:
```
File "/srv/metadataproxy/metadataproxy/routes/mock.py", line 132, in get_security_credentials_slash
role_params = roles.get_role_params_from_ip(request.remote_addr)
File "/srv/metadataproxy/metadataproxy/roles.py", line 59, in timed
result = method(*args, **kw)
File "/srv/metadataproxy/metadataproxy/roles.py", line 198, in get_role_params_from_ip
val = '{0}@{1}'.format(m.group(2), m.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```
This fixes that by making sure the _regex_ matches, not just a substring that is kinda-sorta-similar to what the regex would do. A case where this might happen is if someone were to …
> ensure all-or-nothing for ARN matching a role

- metadataproxy/roles.py
In `roles.py` there are several places where a string representing an envvar (formatted as `key=val`) is split like so:
```python
key, val = e.split('=', 1)
```
It's possible however that these strings can also be formatted as simply `key` due to a nil environment variable being set on the docker container. 
eg: if you launch a container like so: `docker run -e 'FOO' -it ubuntu` when you inspect the container, it's JSON output will look like so:
```
"Env": [
"FOO",
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
],
```
The current method of splitting by directly calling `.split` will cause a stack trace in this event, even if the key which is nil is _not_ something we are looking for. 
To prevent that I've simply added a method that will ensure two items are always …
> Add `split_envvar()` method to return key/val or key/None

- README.md
- metadataproxy/roles.py
- metadataproxy/settings.py
Fixes https://github.com/lyft/metadataproxy/issues/94
Hey friends. The linked issue describes the behaviour we're hoping to see addressed by this PR. In short: metadataproxy caches credentials until they are 5 minutes from expiration; this PR would change that threshold to 15 minutes, and also make it configurable.
I realize changing a default value is not always desirable, but if that's the case, our org is mostly interested in making the expiry configurable, even if changing the default is not possible.
> Make IAM role expiration threshold 15 minutes + configurable

- manifest.yaml
Refactorator would like to apply these changes to your code!  Please shepherd this to production as soon as possible, going through the normal deployment process monitoring this PR as you would any other change.
**You do not need to approve or land this PR. It will be merged automatically. You will still need to deploy the merged commit yourself.**
To reproduce these changes locally, run:
```bash
control ensure control.minimal
control run refactorator.run fix -i metadataproxy -f setdeploystepenvironment
```
This refactorator adds an `environment` to deploy steps where it can be trivially inferred (e.g. the name already contains a valid environment).
Deploy steps whose names cannot be trivially inferred will be skipped for now in favor of revisiting later.
This enables the Deploys team to …
> Refactorator: Apply setdeploystepenvironment in metadataproxy

- CHANGELOG.md
- README.md
- metadataproxy/__init__.py
- metadataproxy/settings.py
- setup.py
aws-vault supports running as an ecs-server, which runs on a random port, on localhost, with a required token. It puts the URL into the environment, and metadataproxy will use that URL, if it's set in the environment. However, docker for mac only allows access to the host through a special hostname. Botocore limits access to a hardcoded set of hostnames and IPs for the URL.
This change patches botocore to inject a provided hostname, if it's set in the environment.
> Add an option to patch boto to support ecs-server mode of aws-vault

- manifest.yaml
Orca was already disabled in this way. The reference can now be dropped.
> Remove orca reference from deploy steps

- README.md
- metadataproxy/roles.py
- metadataproxy/settings.py
We faced very nasty STS issue with metadata proxy. 
One of our production regions is located in the `ap-southeast-1` and by default boto3 is trying to global STS endpoint which is located in the `us-east-1` region. Latency for this requests dramatically decreased within last one and half months and we started to reach timeouts for AWS SDK Credential Provider calls.
Override default endpoint url via environment variable is not an option due to this issue https://github.com/boto/boto3/issues/2099.
Within this PR I've added new env variable for the metadata proxy to be able to support regional STS endpoint and be fully backward compatible to the previous version.
This solved our issue with latency and I believe this can be useful for the community. Would appreciate for the quick response as …
> STS regional endpoints support
